# introduction

tf.nn.embedding_lookup

tf.nn.embedding_lookup_sparse

# envs

python 2.7

In [123]:
from __future__ import print_function
import numpy as np
import tensorflow as tf

tf.nn.embedding_lookup

In [125]:
a = tf.Variable(np.arange(8).reshape(2,4))
b = tf.Variable(np.arange(8,12).reshape(1,4))
c = tf.Variable(np.arange(12, 20).reshape(2,4))

embedded_tensor = tf.nn.embedding_lookup(params=[a,b,c], ids=[1], partition_strategy='div', name="embedding")

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print (sess.run(a))
    print (sess.run(b))
    print (sess.run(c))

    print ("########## embedded_tensor #########")
    print(sess.run(embedded_tensor))


[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]]
########## embedded_tensor #########
[[4 5 6 7]]


tf.nn.embedding_lookup_sparse

In [122]:
a = np.arange(8).reshape(2, 4)
b = np.arange(8, 16).reshape(2, 4)
c = np.arange(16, 24).reshape(2, 4)
print ("a :")
print (a)
print ("b :")
print (b)
print ("c :")
print (c)
a = tf.Variable(a, dtype=tf.float32)
b = tf.Variable(b, dtype=tf.float32)
c = tf.Variable(c, dtype=tf.float32)
idx = tf.SparseTensor(indices=[[0,0], [0,2], [1,0], [1, 1]], values=[1,2,2,0], dense_shape=(2,3))
result = tf.nn.embedding_lookup_sparse([a,b,c], idx, None, partition_strategy='mod', combiner="sum")

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

    res = sess.run(result)
    print ("\n# result here")
    print(res)

a :
[[0 1 2 3]
 [4 5 6 7]]
b :
[[ 8  9 10 11]
 [12 13 14 15]]
c :
[[16 17 18 19]
 [20 21 22 23]]

# result here
[[24. 26. 28. 30.]
 [16. 18. 20. 22.]]
